[env]
term = "xterm-256color"

[font]
size = 10.0

[font.bold]
family = "dejavu sans mono"
style = "Bold"

[font.bold_italic]
family = "dejavu sans mono"
style = "Bold Italic"

[font.italic]
family = "dejavu sans mono"
style = "Italic"

[font.normal]
family = "dejavu sans mono"
style = "Regular"

[colors.cursor]
text = "#000000"
cursor = "#FFFFFF"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#FFFFFF"

[colors.primary]
background = '#000000'
foreground = '#FFFFFF'

[colors.normal]
black =   '#000000'
red =     '#F44243'
green =   '#00CF6B'
yellow =  '#FFD750'
blue =    '#1097CD'
magenta = '#CA5ECE'
cyan =    '#20B2AA'
white =   '#FFFFFF'

[colors.bright]
black =   '#696969'
red =     '#FF2400'
green =   '#03C03C'
yellow =  '#FDDF00'
blue =    '#007FFF'
magenta = '#FF1493'
cyan =    '#00CCCC'
white =   '#FFFFFF'

[colors.hints.end]
background = "#FF00FF"
foreground = "#FFD750"

[colors.hints.start]
background = "#FF0000"
foreground = "#FFD750"

[[hints.enabled]]
regex = "(mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
command = "xdg-open"
hyperlinks = true
persist = true
post_processing = true
mouse.enabled = true
#mouse.mods = "Control"

#[colors.selection]
#background = "#FF0000"
#foreground = "#FFD750"
