[env]
term = "xterm-256color"

[font]
size = 15.0

[font.bold]
family = "dejavu sans mono"
style = "Bold"

[font.bold_italic]
family = "dejavu sans mono"
style = "Bold Italic"

[font.italic]
family = "dejavu sans mono"
style = "Italic"

[font.normal]
family = "dejavu sans mono"
style = "Regular"

[colors.cursor]
text = "#000000"
cursor = "#FFFFFF"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#FFFFFF"

[colors.primary]
background = '#000000'
foreground = '#FFFFFF'

[colors.normal]
black =   '#000000'
red =     '#F44243'
green =   '#00CF6B'
yellow =  '#FFD750'
blue =    '#0087DD'
magenta = '#FA4EFE'
cyan =    '#20B2AA'
white =   '#FFFFFF'

[colors.bright]
black =   '#696969'
red =     '#FF2400'
green =   '#03C03C'
yellow =  '#FDDF00'
blue =    '#007FFF'
magenta = '#FF1493'
cyan =    '#00CCCC'
white =   '#FFFFFF'
